### ISSUE TITLE
Invalid access token 

### ISSUE THREAD

**Issue by fo2sh04** [abjerner/Skybrud.Social.Instagram#10]
instagram.Users.GetUser(long.Parse(InstagramUserId));

this line always return exception of invalid provided access token , 
after some debugging i notice that skybrud use the following Instagram API  https://api.instagram.com/v1/users/ that it's not supported anymore , i think you have to use the following new API 
https://graph.instagram.com/

**Comment by abjerner** [comment]
Hi @fo2sh04,

This package currently supports the [**Instagram Platform API**](https://social.skybrud.dk/instagram/platform-api/) as well as parts of the [**Instagram Graph API**](https://social.skybrud.dk/instagram/graph-api/).

The [**Platform API**](https://social.skybrud.dk/instagram/platform-api/) has been available from not long after Instagram was launched. But in 2018, Instagram started to close parts of this API - for instance the `GetUser` method as you are referring to. Parts of the API still work though, which is why it's still part of the package. But Instagram has described that the remaining parts of the Platform API will be closed "early 2020" - whenever that is. This package is still in beta, but I'd imagine I will remove the parts for the Platform API before making a stable release.

When Instagram announced that the Platform API was being retired, they also announced that they we're going to create the [**Graph API**](https://social.skybrud.dk/instagram/graph-api/) as an alternative - but only for Instagram business accounts. With the latest beta release, parts of this API is supported - primarily for [getting recent media of a business user](https://social.skybrud.dk/instagram/graph-api/endpoints/users/getting-recent-media-of-a-user/). If you have a business account (eg. linked with your Facebook account), this should be what you're looking for.

As the Graph API is targeted business users, Instagram has also introduced the [**Instagram Basic Display API**](https://developers.facebook.com/docs/instagram-basic-display-api), which is then targeted personal Instagram accounts instead (this is the one using the `graph.instagram.com` domain). The plan is that this part will be supported as well, but I don't have a time frame for when this will happen.

I hope that makes sense 😉
