### ISSUE TITLE
GetUserFeed returns error...

### ISSUE THREAD

**Issue by 3wiggle** [abjerner/Skybrud.Social.Instagram#2]
InstagramService service = InstagramService.CreateFromAccessToken(_Settings.Settings["UserAccessToken"].Value);

InstagramUserResponse response = service.Users.GetSelf();

```
        ... process user object (this is successful with 200 and valid user data for access token)
```

InstagramUserFeedResponse UserFeedsTest1 = service.Users.GetUserFeed();
InstagramUserFeedOptions options = new InstagramUserFeedOptions();
               options.MaxId = "1";
               options.Count = 10;
InstagramUserFeedResponse UserFeedsTest2 = service.Users.GetUserFeed(options);

BOTH version of GetUserFeed call return {"Invalid JSON primitive: ." 
This is a brand new project, install of SkyBrud.Social from both Nuget and from GetHub ZIP..
Thanks in advance for any assistance.. this package looks strong...

**Comment by abjerner** [comment]
@3wiggle Instagram has removed the underlying API method, which is why the parsing fails (it now receives an HTML document rather than a JSON response).

Instagram recently made some changes to their API, where no longer being able to get the user feed of the authenticated user was one of them. So this is no longer possible :(

Ideally the methods should also be removed from my package, but I haven't gotten around to that yet.
