### ISSUE TITLE
InstagramUsersResponse

### ISSUE THREAD

**Issue by pghdeveloper** [abjerner/Skybrud.Social.Instagram#6]
Do you know where InstagramUsersResponse is coming from?  I'm able to get InstagramService recognized by doing "using Skybrud.Social.Instagram", but can't seem to find where InstagramUsersResponse originates from.

**Comment by abjerner** [comment]
@pghdeveloper What made you look for the `InstagramUsersResponse` class?

If we're talking NuGet packages and GitHub releases, **Skybrud.Social** is the "old" and still the stable version of Skybrud.Social. It holds implementations for a handful of services - including Instagram. If you use the `Search` method in the *Users* endpoint, you will get an instance of the `InstagramUsersResponse` class you're looking.

Going forward, the implementation for each service will be released as individual packages - eg. **Skybrud.Social.Instagram** for Instagram (which what is this repository is for). This work is still in progress (but will hopefully soon be completed), so these packages are for now released as beta packages.

My reason for using the "beta" term is mostly that I may break things between each beta release, as I'm trying to improve the project structure before eventually pushing a stable release. Otherwise there shouldn't be anything wrong with using the beta releases of **Skybrud.Social.Instagram** instead of the older and stable **Skybrud.Social**.

In the latest beta release of **Skybrud.Social.Instagram**, the `InstagramUsersResponse` is now instead called `InstagramSearchUsersResponse`, so the name better reflects that this is a search for users rather than just a list of users in general.

As I'm going along with the development of the beta releases, I'm also trying to update the documentation so that it will reflect the latest. I can see I haven't updated the page below (which may be the one you have found):

https://social.skybrud.dk/instagram/endpoints/users/search-users/

I will look into fixing that ;)

**Comment by abjerner** [comment]
I've now updated that particular page to work with the latest beta release of **Skybrud.Social.Instagram** (which is `v1.0.0-beta3`). I hope that makes things more clear ;)

Some of the other Instagram pages still seem to be for **Skybrud.Social**. I will look into fixing them as well when I have some more time ;)
