### ISSUE TITLE
Instagram API Platform Deprecation

### ISSUE THREAD

**Issue by Kiruwagaka** [abjerner/Skybrud.Social.Instagram#7]
With the Instagram API Platform Deprecation will you be supporting the new Instagram Graph API anytime soon?

**Comment by natelaff** [comment]
Also curious. I would use the /users/self/media/recent endpoint. Which is basically what I was doing with this anyway. The current method, even using the owner of the token doesn't work.

**Comment by abjerner** [comment]
@Kiruwagaka sorry for the late answer. I haven't made any code for the new Instagram Graph API. The last time I checked, it still didn't offer more than the old Platform API. It may however have changed since then, so I'll give it another look ;)

@natelaff I haven't experienced any problems with `/users/self/media/recent`, as I still use it for a number of websites. Instagram also describes that this part will be deprecated in early 2020, so it should still work for a little over a year.

If it doesn't work in your case, it may depend on the configuration of your app. Unfortunately I don't think I'll can help you with debugging that.

**Comment by biapar** [comment]
So Will be some updates?

**Comment by abjerner** [comment]
Hi everyone,

The most recent beta release (from this Friday) adds some support for the new Graph API - including getting recent media of a user:

https://github.com/abjerner/Skybrud.Social.Instagram/releases/tag/v1.0.0-beta005

I've also added a bit of documentation here:

https://social.skybrud.dk/instagram/graph-api/

**Comment by Giovanni-Mattucci** [comment]
Have the endpoints been updated? I am getting an error response of "This endpoint has been retired" 
It seems Instagram has shut down their old api endpoints https://www.instagram.com/developer 
Does the package support the new endpoints?

**Comment by biapar** [comment]
This package is deprecated. Instagram change the Apis like Facebook.

**Comment by abjerner** [comment]
The package is not deprecated 😉

It's correct that it still contains the code for the old Platform API, which won't work as Instagram has closed down that API. Ideally I should remove the code from the package, as it no longer has any use - but I haven't had the time to do so yet.

Instead of the Platform API, you should now use the Instagram Graph API. For now, this package supports [Getting information about a user](https://social.skybrud.dk/instagram/graph-api/endpoints/users/getting-information-about-a-user/) and [Getting recent media of a user](https://social.skybrud.dk/instagram/graph-api/endpoints/users/getting-recent-media-of-a-user/).

**Comment by biapar** [comment]
Better to say not updated. 
I used it for a site to get photos from Instagram and post from FB, but I get a lots of error because the Apis changed. So I used it only to get the token and then I used FB Api directly.

**Comment by abjerner** [comment]
@biapar was that with the Platform API or the Graph API? As long as the access token has the necessary permissions, I haven't experienced any issues with my implementation for the Graph API.

If you do experience any errors, please feel tree to create an issue, and I'll have a look at it 😉
